/* Generated by ChibiForge - do not edit */
#ifndef CONFIG_H
#define CONFIG_H

#define GREETING "${doc.settings.greeting}"
#define COUNT ${doc.settings.count}
#define ENABLED ${doc.settings.enabled}
#define TARGET "${configuration.target}"

#endif /* CONFIG_H */
