<#-- Simplified board.h for ChibiForge testing -->
/*
 * Board header - generated by ChibiForge.
 */

#ifndef _BOARD_H_
#define _BOARD_H_

/*
 * Board identifier.
 */
#define BOARD_${doc.identification.board_identifier}
#define BOARD_NAME                  "${doc.identification.board_name}"

/*
 * Board oscillators-related settings.
 */
<#if doc.clock_settings.hse_oscillator_mode != "None">
#define STM32_HSECLK                ${doc.clock_settings.hse_frequency}
<#if doc.clock_settings.hse_oscillator_mode == "Bypass">
#define STM32_HSECLK_BYPASS
</#if>
<#else>
#define STM32_HSECLK                0
</#if>
<#if doc.clock_settings.lse_oscillator_mode != "None">
#define STM32_LSECLK                ${doc.clock_settings.lse_frequency}
<#if doc.clock_settings.lse_oscillator_mode == "Bypass">
#define STM32_LSECLK_BYPASS
</#if>
<#else>
#define STM32_LSECLK                0
</#if>

/*
 * Board voltages.
 */
#define STM32_VDD                   ${doc.clock_settings.vdd}

/*
 * MCU type.
 */
#define STM32F4XX

<#if doc.phy_settings.address != "None">
/*
 * Ethernet PHY type.
 */
#define BOARD_PHY_ID                ${doc.phy_settings.id}
<#if doc.phy_settings.mode == "RMII">
#define BOARD_PHY_RMII
</#if>
<#if doc.phy_settings.address != "Autoscan">
#define BOARD_PHY_ADDRESS           ${doc.phy_settings.address}
</#if>

</#if>
#if !defined(_FROM_ASM_)
#ifdef __cplusplus
extern "C" {
#endif
  void boardInit(void);
#ifdef __cplusplus
}
#endif
#endif /* _FROM_ASM_ */

#endif /* _BOARD_H_ */
